local:
  FILENAME: 43353_3555087_150235976_cmp_template.txt.gz
  FTP_HOST: localhost
  FTP_PASSWORD: password
  FTP_PORT: '21'
  FTP_REMOTE_PATH: /43353/
  FTP_USER: jjacobs2000
  S3_BUCKET: bugatchi-data-files
dev:
  FILENAME: 43353_3555087_150235976_cmp_template.txt.gz
  FTP_HOST: aftp.linksynergy.com
  FTP_PASSWORD: asdf*1234
  FTP_PORT: '21'
  FTP_REMOTE_PATH: /43353/
  FTP_USER: jjacobs2000
  S3_BUCKET: bugatchi-data-files
prod:
  FILENAME: 43353_3555087_150235976_cmp_template.txt.gz
  FTP_HOST: aftp.linksynergy.com
  FTP_PASSWORD: asdf*1234
  FTP_PORT: '21'
  FTP_REMOTE_PATH: /43353/
  FTP_USER: jjacobs2000
  S3_BUCKET: bugatchi-data-files
