service: BugatchiMobileDataPipeLine

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-tracing
  - serverless-plugin-lambda-dead-letter
  - serverless-s3-local
  - serverless-offline-scheduler
  - serverless-offline

custom:
  # Import secrets.
  private: ${file(./private.yml)}
  default_stage: ${self:custom.private.stage}
  stage: ${opt:stage, self:custom.default_stage}
  serverless-offline:
    port: 4000
  bucketArn:
    Fn::Join:
    - ''
    - - 'arn:aws:s3:::'
      - Ref: localbucket
      - '/*'
  s3:
    host: 0.0.0.0
    port: 8080
    directory: /tmp

provider:
  name: aws
  stage: dev
  region: us-east-1
  profile: serverless-admin
  runtime: nodejs8.10
  tracing: true
  environment:
    ATHENA_S3_BUCKET: ${file(./config.yml):ATHENA_S3_BUCKET}
    FTP_S3_BUCKET: ${file(./config.yml):FTP_S3_BUCKET}
    FTP_HOST: ${file(./config.yml):${self:custom.stage}.FTP_HOST}
    FTP_PASSWORD: ${file(./config.yml):${self:custom.stage}.FTP_PASSWORD}
    FILENAME: ${file(./config.yml):FILENAME}
    FTP_PORT: ${file(./config.yml):FTP_PORT}
    FTP_USER: ${file(./config.yml):FTP_USER}
    FTP_REMOTE_PATH: ${file(./config.yml):FTP_REMOTE_PATH}
    STAGE: ${self:custom.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "lambda:*"
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "xray:*"
      Resource:
        - "*"
    - Effect: Allow
      Action:
        - sqs:*
      Resource: "*"
    - Effect: Allow
      Action:
        - athena:*
      Resource: "*"

functions:

   transfer:
     handler: transfer/index.handler
     timeout: 10
     deadLetter:
       sqs: transfer-dl-queue
     events:
      - schedule: cron(0 23 * * ? *)

   transform:
     handler: transform/index.handler
     timeout: 10
     deadLetter:
       sqs: transform-dl-queue
     events:
      - s3: ftp

resources:
  Resources:

    athenaS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicReadWrite
        BucketName: "${self:provider.environment.ATHENA_S3_BUCKET}-${self:custom.stage}"
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT, HEAD, POST, DELETE]
              AllowedOrigins: ['*']
              Id: myCORSRuleId1
              MaxAge: '3600'

    S3BucketFtp:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicReadWrite
        BucketName: "${self:provider.environment.FTP_S3_BUCKET}-${self:custom.stage}"
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT, HEAD, POST, DELETE]
              AllowedOrigins: ['*']
              Id: myCORSRuleId1
              MaxAge: '3600'

    TransformLambdaPermissionFtpS3:
      Type: "AWS::Lambda::Permission"
      Properties:
        FunctionName:
          "Fn::GetAtt":
            - TransformLambdaFunction
            - Arn
        Principal: "s3.amazonaws.com"
        Action: "lambda:InvokeFunction"
        SourceAccount:
          Ref: AWS::AccountId
        SourceArn: "arn:aws:s3:::${self:provider.environment.FTP_S3_BUCKET}-${self:custom.stage}"

package:
  include:
    - transfer/**
    - transform/**
  exclude:
    - test/**
    - .idea
    - docker-compose.yml
    - README.md





